###

GET http://localhost:3001/api/v1/visitors



###
GET http://localhost:3001/



### Creating a new Project
POST https://crispengari.onrender.com/api/v1/project/add
content-type: application/json

{
  "name": "ai-detector",
  "description": "🤖 Detecting AI generated text in real time using Deep-Leaning.",
  "longDescription":  "🤖 Detecting AI generated text in real time using Deep-Leaning. This repository contain a GraphQL Server served to a Next.js application to detect AI generated text.",
  "url": "https://github.com/CrispenGari/ai-detector.git",
  "cover":"/covers/ai-detector.png",
  "languages": ["TypeScript", "Python"],
  "projectType":"Artificial Intelligence",
  "year": 2024
}


### Getting Projects

GET https://crispengari.onrender.com/api/v1/projects


### Getting a project
GET http://localhost:3001/api/v1/project/62e53e8298301c5addb444c1

### Getting a project
DELETE http://localhost:3001/api/v1/project/62e64feca46683e420b4b15e

### Updating a project

PUT https://crispengari.onrender.com/api/v1/project/63a46c7b2f91658019bcfce8
content-type: application/json

{
   "cover": "/covers/restaurant.jpg",
}
