###

GET http://localhost:3001/api/v1/visitors

###
GET http://localhost:3001/

### Creating a new Project
POST https://crispengari.onrender.com/api/v1/project/add
content-type: application/json

{
  "name": "dfmaster",
  "description": "👾 This is a simple vscode extension that reads cvs, tsv, etc file into a dataframe table.",
  "longDescription":  "This is the Visual Studio Code extension that converts data for files with extensions tsv, json and csv into DataFrame tables.",
  "url": "https://github.com/CrispenGari/dfmaster",
  "cover":"/covers/dfmaster.png",
  "languages": ["TypeScript"],
  "projectType":"Web Development",
  "year": 2023
}


### Getting Projects

GET https://crispengari.onrender.com/api/v1/projects


### Getting a project
GET http://localhost:3001/api/v1/project/62e53e8298301c5addb444c1

### Getting a project
DELETE http://localhost:3001/api/v1/project/62e64feca46683e420b4b15e

### Updating a project

PUT https://crispengari.onrender.com/api/v1/project/63a46c7b2f91658019bcfce8
content-type: application/json

{
   "cover": "/covers/restaurant.jpg",
}
