export { default as Barner } from "./Barner/Barner";
export { default as NavItem } from "./NavItem/NavItem";
export { default as Footer } from "./Footer/Footer";
export { default as DBarnner } from "./DBarnner/DBarnner";
export { default as AboutContent } from "./AboutContent/AboutContent";
export { default as Tech } from "./Tech/Tech";
export { default as Nav } from "./Nav/Nav";
export { default as Form } from "./Form/Form";
export { default as Header } from "./Header/Header";
